GET http://localhost:3000/books HTTP/1.1

###
GET http://localhost:3000/books/2 HTTP/1.1

###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
     "title": "Java a fondo ",
            "author": "Pablo Sznajdleder",
            "year": 2017
}

###
PUT http://localhost:3000/books/13 HTTP/1.1
Content-Type: application/json

{
    "year": 1999
}

###
DELETE http://localhost:3000/books/14 HTTP/1.1
